/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BondDetails": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BondStatistics": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BondsUpdater": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBondQuotes": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBonds": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetProfile": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IssuerProfiles": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NotificationSender": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Profiles": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "UpdateProfile": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}