import type { NextPage } from 'next';
import Head from 'next/head';
import Box from "@mui/material/Box";
import BondViewer from '../components/BondsViewer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Catalyst Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component='main' sx={{
        minHeight: '100vh',
        pt: 1,
        backgroundColor: 'lightblue'
      }}>
        <BondViewer />
      </Box>
    </>
  )
}

export default Home;
